// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Account struct {
	ID        int64        `json:"id"`
	Owner     string       `json:"owner"`
	Balance   int64        `json:"balance"`
	Currency  string       `json:"currency"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Entry struct {
	ID        int64        `json:"id"`
	OwnerID   int64        `json:"owner_id"`
	Amount    int64        `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transfer struct {
	ID           int64        `json:"id"`
	FromAcountID int64        `json:"from_acount_id"`
	ToAcountID   int64        `json:"to_acount_id"`
	Amount       int64        `json:"amount"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
